### PR TITLE
Add HC-SR04 ultrasonic sensor

### PR DESCRIPTION
**Pull request by iLLiac4**
Updated fzz file for echo sensor relay and h-bridge.
[wiring-relay_hc-sr04.zip](https://github.com/aenniw/ARDUINO/files/4570906/wiring-relay_hc-sr04.zip)
[wiring-h-bridge_hc-sr04.zip](https://github.com/aenniw/ARDUINO/files/4570914/wiring-h-bridge_hc-sr04.zip)

### CODE REVIEW

**Comment by aenniw** [comment]
- [ ] watchdog timeouts
- [ ] watchdog enabled by compile flag
- [ ] watchdog should trigger without any sensor
- [ ] extract config constants to separate file or `platformio.ini`

**Comment by bisselke** [comment]
What is the estimated release date of this feature? I already have everything hooked up, with the HC sr04 sensor in place, and get a Er 4. Thanks for all the hard work!

**Comment by aenniw** [comment]
- [ ] extract `STOP_POS_DIFF` to settings
- [ ] extract `MINIMUM_POS_CHANGE` to settings

**Comment by aenniw** [comment]
update `wd` settings for HC-SR04
```c
#define WATCHDOG_TIMEOUT 2000
#define WATCHDOG_DEADLOCK_CHANGE 20
#define WATCHDOG_OTHER_CHANGE 100
#define WATCHDOG_TOLERANCE 20
```

**Pull request merged**
